name: Reusable Workflow

on:
  workflow_call:

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Set output value
        id: set_output
        run: |
          echo "example_value=Hello, World!" > output.txt

      - name: Upload output as artifact
        uses: actions/upload-artifact@v3
        with:
          name: example-output
          path: output.txt
