name: Reusable Workflow

on:
  workflow_call:
    outputs:
      example_output:
        description: 'An example output value'
        value: ${{ steps.set_output.outputs.example_value }}

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Set output value
        id: set_output
        run: echo "example_value=Hello, World!" >> $GITHUB_ENV
